### ISSUE TITLE
anyType + anySimpleType issue

### ISSUE THREAD

**Issue by Adraesh** [goetas-webservices/xsd2php#103]
Hi!

First of all, thank you very much for this lib!

I am trying to make it work without success bellow my issue:
```
In SchemaReader.php line 1056:
                                                                                                             
  Can't find type named {http://www.opengis.net/gml/3.2}#anyType, at line 21 in http://schemas.opengis.net/  
  gml/3.2.1/gmlBase.xsd                                                                                      
                                                                                                             

In Schema.php line 100:
                                                                       
  Can't find the Type named {http://www.opengis.net/gml/3.2}#anyType. 
```

Though anyType and anySimpleType are well set to their alias as following:

```
aliases: 
        'http://www.opengis.net/gml/3.2':
            anyType: 'Jms\Handler\GmlAnyTypeHandler'
            anySimpleType: 'Jms\Handler\GmlAnySimpleTypeHandler'
```

The related handler's classes are registered as service and tag to jms_serializer.subscribing_handler as following:

```
App\Jms\Handler\GmlAnyTypeHandler:
       public: true
       tags:
           - { name: jms_serializer.subscribing_handler }

    App\Jms\Handler\GmlAnySimpleTypeHandler:
       public: true
       tags:
           - { name: jms_serializer.subscribing_handler }
```

Any idea? Thank you in advance.
