### ISSUE TITLE
Use of slashes / quotes in config.yml

### ISSUE THREAD

**Issue by holtkamp** [goetas-webservices/xsd2php#11]
While following the instructions in the ```README.md```, I had to tweak my ```config.yml``` a bit to get PHP class and YML metadata for JMS Serializer generation working.

Note sure whether this depends on the operating systeem / file system, but it might be good to double check it. I am using macOS Sierra 10.12.1.

**breaking: use of slashes**

- example uses for ```destinations_php```:  ```'TestNs/MyApp': soap/src```, this results in an error:

```
[GoetasWebservices\Xsd\XsdToPhp\PathGenerator\PathGeneratorException]        
  Can't find a defined location where save 'X\Y\Z\Classname' object     
```
when changing it to ```'TestNs\MyApp': soap/src``` it works (note that the forward slash has changed to a backward slash.

**can be simplified (?): use of quotes**
The ```config.yml``` contains single quotes, why is that? When removed it still works?

For example:  ```TestNs\MyApp: soap/src``` works as well. Removing all single quotes from my ```config.yml``` breaks nothing...

**Comment by goetas** [comment]
/ are for mac Unix and Linux based systems 
\ are for windows 

Not sure if this should be documented

**Comment by goetas** [comment]
Was this the issue?

**Comment by goetas** [comment]
Quoting depends on yaml specifications.. and I'm not really deep into it

**Comment by holtkamp** [comment]
>Not sure if this should be documented

Think this would be useful yes... I really had to puzzle a bit until I got it working and started doubting my configuration. A short comment can already help starting users:

```yaml
destinations_php:
    #On Windows
    TestNs/MyApp: soap/src 
    #On Mac, Unix, Linux, etc
    TestNs\MyApp: soap/src 
```


>Quoting depends on yaml specifications.. and I'm not really deep into it

Ok, well, my personal approach would be to leave as little to interpretation as possible, so either use it consistently (both for the key AND the value):
```yaml
destinations_php:
    #On Windows
    'TestNs/MyApp': 'soap/src'
    #On Mac, Unix, Linux, etc
    'TestNs\MyApp': 'soap/src'
```

or not at all:
```yaml
destinations_php:
    #On Windows
    TestNs/MyApp: soap/src 
    #On Mac, Unix, Linux, etc
    TestNs\MyApp: soap/src 
```

just my 2 cents, not big issues 😄
