### ISSUE TITLE
Not working with Symfony

### ISSUE THREAD

**Issue by link365dev** [goetas-webservices/xsd2php#119]
In Symfony 4.4, I added the config file: `project-name/config/packages/xsd2php.yaml`
containing
```
xsd2php:
  namespaces: # (required) defines the mapping between XML namespaces and PHP namespaces. (in the example we have the http://www.example.org/test/ XML namespace mapped to TestNs\MyApp)
    'http://www.example.org/test/': 'TestNs\MyApp'
  destinations_php: # (required) specifies the directory where to save the PHP classes that belongs to TestNs\MyApp PHP namespace. (in this example TestNs\MyApp classes will be saved into soap/src directory.
    'TestNs\MyApp': soap/src
#    'TestNs\MyApp': soap\src  #  on Windows

  destinations_jms: # (required) specifies the directory where to save JMS Serializer metadata files that belongs to TestNs\MyApp PHP namespace. (in this example TestNs\MyApp metadata will be saved into soap/metadata directory.
    'TestNs\MyApp': soap/metadata
#    'TestNs\MyApp': soap\metadata  #  on Windows

#  Uncomment this section if you want to have also symfony/validator metadata to be generated from XSD
#  destinations_validation:
#    'TestNs\MyApp': soap/validation
#    'TestNs\MyApp': soap\validation  #  on Windows

  aliases: #  (optional) specifies some mappings that are handled by custom JMS serializer handlers. Allows to specify to do not generate metadata for some XML types, and assign them directly a PHP class. For that PHP class is necessary to create a custom JMS serialize/deserialize handler.
    'http://www.example.org/test/':
      MyCustomXSDType:  'MyCustomMappedPHPType'
  naming_strategy: short # default (optional) specifies the naming strategy to use when converting XML names PHP classes.
  path_generator: psr4 # default (optional) specifies the strategy to use for path generation and file saving
#  known_locations: # (optional) override remote location with a local file.
#    "http://www.example.org/test/somefile.xsd": somefile.xsd
#  known_namespace_locations: (optional) Specify schema location by namespace. This can be used to read schemas which import namespaces but do not specify schemaLocation attributes.
#    "urn:veloconnect:catalog-1.1": xsd/catalog-1.1.xsd
```

But, when loading the Symfony project in my server, I got:

```
php_1         | !!    There is no extension able to load the configuration for "xsd2php" (in "/sr
php_1         | !!    v/api/config/packages/xsd2php.yaml"). Looked for namespace "xsd2php", found
php_1         | !!     ""framework", "security", "mercure", "twig", "doctrine", "api_platform", "
php_1         | !!    nelmio_cors", "web_profiler", "maker", "doctrine_mongodb", "vich_uploader""
php_1         | !!     in /srv/api/config/packages/xsd2php.yaml (which is loaded in resource "/sr
php_1         | !!    v/api/config/packages/xsd2php.yaml").
php_1         | !!
php_1         | !!
php_1         | !!  In YamlFileLoader.php line 713:
php_1         | !!
php_1         | !!    There is no extension able to load the configuration for "xsd2php" (in "/sr
php_1         | !!    v/api/config/packages/xsd2php.yaml"). Looked for namespace "xsd2php", found
php_1         | !!     ""framework", "security", "mercure", "twig", "doctrine", "api_platform", "
php_1         | !!    nelmio_cors", "web_profiler", "maker", "doctrine_mongodb", "vich_uploader""
php_1         | !!    .
```

The config is located with all the other configuration yamls. Is that the correct location?
