### ISSUE TITLE
Validation metadata setting max count = 2 to elements with no maxOccurs. 

### ISSUE THREAD

**Issue by fell-lucas** [goetas-webservices/xsd2php#135]
Hello, I have the following structure in my XSD schema:
```xml
<xs:element name="Docentes">
  <xs:complexType>
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="Docente">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Nome" type="TNome"/>
            <xs:element name="Titulacao" type="TTitulacao"/>
          </xs:sequence>
         </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
```
When generating validation metadata, this is the related yml file generated:
```yaml
docentes:
            -
                NotNull:
                    groups:
                        - xsd_rules
            -
                Count:
                    min: 1
                    max: 2
                    groups:
                        - xsd_rules
            -
                Valid: null
```
Even though the sequence inside the parent element has an "unbounded" maxOccurs, the validator returns the following violation: (in this case, there are 4 elements, and it's complaining because it thinks it should only contain 2 max.)

![image](https://user-images.githubusercontent.com/47724710/117295258-ff0fc000-ae49-11eb-8f5b-9e73cedbde28.png)

Removing "max" from count in the generated yaml file fixes the issue.

```yaml
Count:
  min: 1
  groups:
    - xsd_rules
```
