### ISSUE TITLE
Incorrect JMS namespace for local list element declarations

### ISSUE THREAD

**Issue by rtek** [goetas-webservices/xsd2php#15]
Consider the following XSD:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" targetNamespace="TEST_NS" xmlns:tns="TEST_NS"
           xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified">

    <xs:complexType name="childType">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="child" type="tns:childType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

```

And the JMS generated:
```yaml
TestSchema\Root:
    xml_root_name: root
    xml_root_namespace: TEST_NS
    properties:
        child:
            expose: true
            access_type: public_method
            serialized_name: child
            accessor:
                getter: getChild
                setter: setChild
            xml_list:
                inline: true
                entry_name: child
                namespace: TEST_NS
            type: array<TestSchema\ChildTypeType>

```

In this case, the namespace for root/child should be not defined since the local elements are unqualified.

The desired serialization is:
```xml
<root xmlns="TEST_NS">
    <child xmlns="">
        <id>str</id>
    </child>
</root>
```

Instead of:

```xml
<root xmlns="TEST_NS">
    <child>
        <id>str</id>
    </child>
</root>
```

It seems like the YAMLConverter assumes that elementFormDefault="qualified" when resolving namespaces for lists.
