### ISSUE TITLE
CDATA sections not being disabled in XML despite setting xml_cdata to false in goetas-webservices/xsd2php

### ISSUE THREAD

**Issue by NathanaelSantos** [goetas-webservices/xsd2php#155]
```
"require": {
    "goetas-webservices/xsd2php-runtime": "^0.2.16"
  },
"require-dev": {
    "goetas-webservices/xsd2php": "^0.4.7"
  }
```

```
idEscola:
            expose: true
            access_type: public_method
            serialized_name: idEscola
            xml_element:
                cdata: false
                namespace: 'http://www.tce.se.gov.br/sagres2023/xml/sagresEdu'
            accessor:
                getter: getIdEscola
                setter: setIdEscola
            type: int
```

In my config.yml:

```
  configs_jms:  #optional
    xml_cdata: false # Disables CDATA
```

The generated XML:
```
<entry>
      <id_escola><![CDATA[28022386]]></id_escola>
      <turma/>
      <diretor>
        <cpf_diretor><![CDATA[39353893534]]></cpf_diretor>
        <nr_ato><![CDATA[]]></nr_ato>
      </diretor>
      <cardapio/>
</entry>
```

It appears that despite setting xml_cdata to false, the XML still contains CDATA sections. This could be a bug in the library "goetas-webservices/xsd2php" ?
