### ISSUE TITLE
Can't Load File & Can't fund a PHP namespace

### ISSUE THREAD

**Issue by Neve12ende12** [goetas-webservices/xsd2php#17]
My config.yml

xsd2php:
  namespaces:
    'http://cufxstandards.com/v3/': 'cufx'
  destinations_php:
    'cufx': 'cufx/src'
  destinations_jms:
    'cufx': 'cufx/metadata'    
  naming_strategy: short
  path_generator: psr4

xsd2php convert config.yml D:\nginx\html\phoenix\vendor\bin\xsd\*.xsd -> Can't load the file

When I try xsd2php convert config.yml D:\nginx\html\phoenix\vendor\bin\xsd\Account.xsd -> Can't find PHP namespace to  'http://cufxstandards.com/v3/Account.xsd' namespace

**Comment by goetas** [comment]
> Can't find PHP namespace to 'http://cufxstandards.com/v3/Account.xsd' namespace

means that some of your XML files is declaring `http://cufxstandards.com/v3/Account.xsd` as namespace, so you have to add it to your `config.yml`, example:

```yml
xsd2php:
  namespaces:
    'http://cufxstandards.com/v3/': 'cufx'
    'http://cufxstandards.com/v3/Account.xsd': 'cufx\Account'
  destinations_php:
    'cufx': 'cufx/src'
  destinations_jms:
    'cufx': 'cufx/metadata'
```

keep in mind that in XML namespaces do not have any hierarchy
