### ISSUE TITLE
YAML - Nested element does not receive correct namespace 

### ISSUE THREAD

**Issue by jayvdg** [goetas-webservices/xsd2php#22]
Even though a nested element may reside in it's own namespace, the parents namespace is still used in the YAML.

Example:

```xml
<xs:schema elementFormDefault="qualified" targetNamespace="http://www.example.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://www.example2.com">
    <xs:import namespace="http://www.example2.com" schemaLocation="data2.xsd"/>
    <xs:complexType name="complexType1">
        <xs:sequence>
            <xs:element name="ElementList" type="ns2:ElementList"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
```

The imported schema contains:

```xml
<xs:schema elementFormDefault="qualified" targetNamespace="http://www.example2.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="ElementList">
        <xs:sequence>
            <xs:element maxOccurs="5" name="Element" type="Element"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Element">
        <xs:attribute name="attribute" type="xs:string" />
    </xs:complexType>
</xs:schema>

```

Will become:

```yaml
properties:
        ElementList:
            ...
            xml_list:
                ...
                entry_name: Element
                namespace: 'http://www.example.com'
            ...
```

When it should be:

```yaml
properties:
        ElementList:
            ...
            xml_list:
                ...
                entry_name: Element
                namespace: 'http://www.example2.com'
            ...
```

I have created a PR in which this should be fixed: #21
