### ISSUE TITLE
Make simplifying lists of simple elements optional

### ISSUE THREAD

**Issue by jayvdg** [goetas-webservices/xsd2php#24]
Whenever I have an element without any attributes that is a list of elements of only 1 type, the generator simplifies this into an array of that nested element. This makes sense, but in some cases I need the list element to be present in the serialized XML, even if it's empty. 
An empty array won't be serialized, but an empty element will. I suggest making the "simplifying" of this type of list optional.

I'm not entirely sure how to describe this properly, so let's do it by example.

Given this schema:

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="MainElement">
        <xs:sequence>
            <xs:element name="ElementList">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="NestedElement" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
```

The current output would be (simplified): 

```yaml
MainElementType:
    properties:
        ElementList:
            expose: true
            access_type: public_method
            serialized_name: ElementList
            type: array<integer>
            xml_list:
                inline: false
                entry_name: NestedElement
```

While in some cases I need this to be:

```yaml
MainElementType:
    properties:
        ElementList:
            expose: true
            access_type: public_method
            serialized_name: ElementList
            type: MainElementType\ElementListAType
```

The same goes for the generated PHP code. The "ElementListAType" class is already always generated, but ``MainElement::setElementList()`` expects  the array, and not the object. 

I propose to add a configuration option that enables or disables this "simplifying", with the default still being enabled. I'm already working on a PR for this and will link it shortly.
