### ISSUE TITLE
Add "skip_when_empty" to xml_list options

### ISSUE THREAD

**Issue by jayvdg** [goetas-webservices/xsd2php#26]
As discussed in #24, all empty lists are currently skipped during serialization because this is the default (https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/Annotation/XmlCollection.php#L41).

I propose to add the option ``skip_when_empty`` in the YAML to all lists, and setting it to false whenever the element has a ``minOccurs`` of more than 0. 

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="MainElement">
        <xs:sequence>
            <xs:element name="RequiredElementList">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="NestedElement" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="OptionalElementList" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="NestedElement" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
```

Would result in:

```yaml
MainElementType:
    properties:
        requiredElementList:
            expose: true
            access_type: public_method
            serialized_name: RequiredElementList
            type: array<integer>
            xml_list:
                inline: false
                entry_name: NestedElement
                skip_when_empty: false
        optionalElementList:
            expose: true
            access_type: public_method
            serialized_name: RequiredElementList
            type: array<integer>
            xml_list:
                inline: false
                entry_name: NestedElement
                skip_when_empty: true
```
