### ISSUE TITLE
How generate classes from single .xsd

### ISSUE THREAD

**Issue by errogaht** [goetas-webservices/xsd2php#29]
Hello! Your library looks great. Thanks! But iam don't understand how use it. I have this xsd
http://www.opencorpora.org/export/dict/dict.opcorpora.xsd

I want to generate php classes from it.
But I'm only get empty folders. 
Please help me. May be you can provide config.yml and cmd example for my schema?

**Comment by goetas** [comment]
something as? 

```yml
xsd2php:
  namespaces:
    '': 'TestNs/MyApp'
  destinations_php:
    'TestNs/MyApp': my/src
  destinations_jms:
    'TestNs/MyApp': my/metadata
```

and 
```
vendor/bin/xsd2php convert config.yml http://www.opencorpora.org/export/dict/dict.opcorpora.xsd
```
