### ISSUE TITLE
Problem creating sample XML using generated PHP classes and JMS Serializer metadata

### ISSUE THREAD

**Issue by kiranphp** [goetas-webservices/xsd2php#34]
Hii,

I have a requirement to generate sample XML from XSD files using PHP.I came across this library and followed the initial steps and it worked fine and generated PHP classes and JMS metadata files.But now I am a little bit confused as to how I could generate the XML file (which is I really wanted) using the generated PHP classes and JMS metadata.I am working on Ubuntu 17 OS.My XSD file is given below.

**Update: Currently able to generate XML file but type validation note working.Please look at the comment below.**

Shipment.xsd
```
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="shiporder">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="orderperson" type="xs:string"/>
        <xs:element name="shipto">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="address" type="xs:string"/>
              <xs:element name="city" type="xs:string"/>
              <xs:element name="country" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="item" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="note" type="xs:string" minOccurs="0"/>
              <xs:element name="quantity" type="xs:positiveInteger"/>
              <xs:element name="price" type="xs:decimal"/>
            </xs:sequence>
            <xs:attribute name="maxid" default="xnn" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="orderid" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

The steps I followed is given below.

1. First I created the `config.yml` file

```
# config.yml
# Linux Users: PHP Namespaces use back slash \ rather than a forward slash /
# So for destinations_php, the namespace would be TestNs\MyApp

xsd2php:
  namespaces:
    '': 'TestNs/MyApp'
  destinations_php: 
    'TestNs\MyApp': soap/src
  destinations_jms:
    'TestNs\MyApp': soap/metadata
  aliases: # optional
    '':
      MyCustomXSDType:  'MyCustomMappedPHPType'
  naming_strategy: short # optional and default
  path_generator: psr4 # optional and default
```

2. From the terminal I give the command 
`vendor/bin/xsd2php convert config.yml files/shipment.xsd`

The command run succesfull and I noticed the soap directory was created and inside that there are two subdirectories` soap/src` and `soap/metadata`.Inside src folder it generated the PHP files and inside metadata folder it generated the yml files.Now how can I create the XML using these generated PHP classes and yml files.
![xml](https://cloud.githubusercontent.com/assets/13343880/26387520/f292c980-406b-11e7-8b30-1a3a1fc0b7a9.png)
