### ISSUE TITLE
Can't find a PHP namespace to '' namespace

### ISSUE THREAD

**Issue by mariusz-buk** [goetas-webservices/xsd2php#64]
When executing vendor\bin\xsd2php convert config.yml ovu.xsd I get error 
"Can't find a PHP namespace to '' namespace".

Attached xsd and yml files. What I do wrong?

[ovu.zip](https://github.com/goetas-webservices/xsd2php/files/1922926/ovu.zip)

**Comment by Sevavietl** [comment]
Your `xsd` has no namespace, so config should look like this:

```yml
xsd2php:
  namespaces:
    '': 'Warehouse'
  destinations_php: 
    'Warehouse': classes
  destinations_jms:
    'Warehouse': classes    
  naming_strategy: short
  path_generator: psr4
```
