### ISSUE TITLE
OTA – ListOfRPHType not found

### ISSUE THREAD

**Issue by tpraxl** [goetas-webservices/xsd2php#71]
I'm using xsd2php to generate classes for OTA 2003/05 / 2014A-1.0.

Until now, everything went fine. However, there's an issue with a simpleType that is not generated. I tried to alias the type without success.

```
Class 'Hsp\latest\ListOfRPHType' not found in […]generated/v2014A-1-0/src/ResGuestRPHsType.php on line 11
```

My configuration:
```yaml
# see https://github.com/goetas-webservices/xsd2php
xsd2php:
  namespaces:
    '': 'Hsp\latest'
    'http://www.opentravel.org/OTA/2003/05': 'Hsp\latest'
    'http://www.opentravel.org/OTA/2003/05/common': 'Hsp\latest'
  destinations_php:
    'Hsp\latest': generated/v2014A-1-0/src
  destinations_jms:
    'Hsp\latest': generated/v2014A-1-0/meta
```

And here's the generated code that causes the problem:

```php
<?php

namespace Hsp\latest;

/**
 * Class representing ResGuestRPHsType
 *
 * A collection of unsigned integers serving as reference placeholders, and used as an index identifying which guests occupy this room
 * XSD Type: ResGuestRPHsType
 */
class ResGuestRPHsType extends ListOfRPHType
{


}
```

ListOfRPH is an xs:simpleType in OTA_SimpleTypes.xsd. ListOfRPHType is not generated and I can't find a way to prevent xsd2php from referencing it.

Can anyone help me with a workaround or solution?
