### ISSUE TITLE
Serialization of namespaces according to XSD not working

### ISSUE THREAD

**Issue by aat2703** [goetas-webservices/xsd2php#78]
Hi guys

I've successfully converted my XSD to metadata & PHP classes in proper namespaces.

My problem is that it seems that XSD2PHP doesn't add the correct namespaces to root elements and child nodes it seems... And therefor is not valid according to the XSD schema

XSD: https://github.com/Skatteetaten/saf-t/blob/master/Norwegian_SAF-T_Cash_Register_Schema_v_1.00.xsd

config.yml
``` yml
xsd2php:
  namespaces:
    'urn:StandardAuditFile-Taxation-CashRegister:NO': 'countries\no\saft\xsd2php'
  destinations_php:
    'countries\no\saft\xsd2php': xsd2php
  destinations_jms:
    'countries\no\saft\xsd2php': xsd2php/metadata
  naming_strategy: 'long'

```

test.xml - output from xsd2php
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <id>1</id>
  <header>
    <fiscal_year><![CDATA[2018]]></fiscal_year>
  </header>
  <company>
    <company_name><![CDATA[QuickOrder]]></company_name>
    <street_address/>
    <postal_address/>
    <location/>
  </company>
</result>


```

script.php
``` php
		$AuditFile = new Auditfile();

		$HeaderAType = new Auditfile\HeaderAnonymousType();

		$HeaderAType->setFiscalYear('2018');

		$AuditFile->setHeader(
			$HeaderAType
		);

		$Company = new Auditfile\CompanyAnonymousType();

		$Company->setCompanyName('TestCompany');

		$AuditFile->setCompany(
			$Company
		);

		$AuditFile->setId(1);

		$serializerBuilder = SerializerBuilder::create();

		$serializerBuilder->addMetadataDir(APP_PATH . '/common/countries/no/saft/xsd2php/metadata/');

		$serializerBuilder->configureHandlers(function (HandlerRegistry $handler) use ($serializerBuilder) {

			$serializerBuilder->addDefaultHandlers();

			$handler->registerSubscribingHandler(new BaseTypesHandler());
			$handler->registerSubscribingHandler(new XmlSchemaDateHandler());

		});

		$serializer = $serializerBuilder->build();

		$newXml = $serializer->serialize($AuditFile, 'xml');

		$testFile = __DIR__ . '/../../common/countries/no/saft/examples/test.xml';

		if(is_file($testFile)):
			unlink($testFile);
		endif;

		$file = fopen($testFile, "w");

		fwrite($file, $newXml);
		fclose($file);

		$XSDValidator = new XSDValidator();

		$XSDValidator->setXMLFile(
			__DIR__ . '/../../common/countries/no/saft/examples/test.xml'
		)
		->setXSDFile(
			__DIR__ . '/../../common/countries/no/saft/xsd/Norwegian_SAF-T_Cash_Register_Schema_v_1.00.xsd'
		)
		->validate();

```
