### ISSUE TITLE
Add Namepace for conversion

### ISSUE THREAD

**Issue by KupueIIIKo** [goetas-webservices/xsd2php#79]
For starters, I apologize for my English. I use translator )

I have an XSD with data types.

[Types.txt](https://github.com/goetas-webservices/xsd2php/files/2698724/Types.txt)

The namespace http://zakupki.gov.ru/223fz/types/1 does not meet the PSR to split normally into directories (((
When I try to extract another file! He is requesting this namespace! How to add it to the * .yml file?

For example, the file used with this namespace.
[agencyBlockInfo.txt](https://github.com/goetas-webservices/xsd2php/files/2698726/agencyBlockInfo.txt)
I sit for a week and can not understand! How to unpack the first and second files! So in a bundle I could create a second file. Thank you in advance.

**Comment by goetas** [comment]
Namespaces are assigned based on the configs you have defined... 
see https://github.com/goetas-webservices/xsd2php#usage

As example in your case:


```yml

xsd2php:
  namespaces:
    'http://zakupki.gov.ru/223fz/types/1': 'MyApp\GovRu'
  destinations_php: 
    'MyApp\GovRu': soap/src
  destinations_jms:
    'MyApp\GovRu': soap/metadata

```
